version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique
      - name: orders
        columns:
          - name: id
            tests:
              - not_null
              - unique
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 100, period: hour}
  - name: stripe
    database: raw
    tables:
      - name: payment
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: orderid
            tests:
              - not_null
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 100, period: hour}
